# Generated by Django 5.0.6 on 2024-11-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='code',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(default='no name', max_length=122),
        ),
    ]
