# Generated by Django 5.0.6 on 2024-11-23 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_file_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='code',
            new_name='content',
        ),
        migrations.AddField(
            model_name='file',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 23, 7, 19, 14, 504705)),
        ),
    ]
