# Generated by Django 5.0.6 on 2024-11-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_file_code_alter_file_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(default='no name', max_length=255),
        ),
    ]
